# Generated by Django 5.0.3 on 2024-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0002_site_age_site_email_site_favorite_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=4),
        ),
    ]
