# Generated by Django 5.0.3 on 2024-03-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0003_alter_site_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='today_date',
        ),
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
