# Generated by Django 5.0.3 on 2024-03-24 22:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0005_site_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
