# Generated by Django 5.0.3 on 2024-03-25 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0008_alter_site_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-title']},
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='site_survey_date_ad_7566ea_idx',
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['-title'], name='site_survey_title_35051c_idx'),
        ),
    ]
