# Generated by Django 5.0.3 on 2024-03-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0009_alter_site_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='site_survey_title_35051c_idx',
        ),
    ]
