# Generated by Django 5.0.3 on 2024-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0010_remove_site_site_survey_title_35051c_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='favorite_fruit',
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('WAWA', 'Wawa'), ('SHEETZ', 'Sheetz'), ('THORNTONS', 'Thorntons'), ('ATT', 'AT&T'), ('VERIZON', 'Verizon')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
