# Generated by Django 5.0.3 on 2024-03-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0011_remove_site_favorite_fruit_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('Wawa', 'Wawa'), ('Sheetz', 'Sheetz'), ('Thorntons', 'Thorntons'), ('AT&T', 'AT&T'), ('Verizon', 'Verizon')], max_length=100),
        ),
    ]
