# Generated by Django 5.0.3 on 2024-03-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0014_rename_address_site_city_site_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
