# Generated by Django 5.0.3 on 2024-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0018_alter_site_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='file_upload',
            field=models.FileField(upload_to='site_surveys/media/%Y/%m/%d/'),
        ),
    ]
