# Generated by Django 5.0.3 on 2024-03-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0019_alter_site_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='age',
        ),
        migrations.RemoveField(
            model_name='site',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='site',
            name='text',
        ),
    ]
