# Generated by Django 5.0.3 on 2024-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0025_alter_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='idf',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='mdf',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='router_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='router_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='server_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='server_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='switch_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='switch_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
