# Generated by Django 5.0.3 on 2024-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0026_site_idf_site_mdf_site_router_one_site_router_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('FL', 'Florida'), ('OH', 'Ohio'), ('PA', 'Pennsylvania')], max_length=2),
        ),
    ]
