# Generated by Django 5.0.3 on 2024-03-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0029_alter_site_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[(None, 'Site Type'), ('Wawa', 'Wawa'), ('Sheetz', 'Sheetz'), ('Thorntons', 'Thorntons'), ('AT&T', 'AT&T'), ('Verizon', 'Verizon')], max_length=25),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(),
        ),
    ]
