# Generated by Django 5.0.3 on 2024-03-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0030_alter_site_email_alter_site_site_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['title']},
        ),
    ]
