# Generated by Django 5.0.3 on 2024-03-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0033_alter_site_back_alter_site_front_alter_site_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='idf',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='mdf',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='router_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='router_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='server_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='server_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='switch_one',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='switch_two',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
