# Generated by Django 5.0.3 on 2024-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_surveys', '0034_alter_site_idf_alter_site_mdf_alter_site_router_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date_added'),
        ),
    ]
